// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2026 RoidMC Studios
//
// Dynamic Client Registration (RFC 7591) and
// Dynamic Client Registration Management (RFC 7592) implementation.

package op

import (
	"context"
	"time"
)

// ClientRegistrationStorage is the interface for storing and managing
// dynamically registered OAuth 2.0 / OpenID Connect clients.
// Implement this interface in your storage layer to support RFC 7591 and RFC 7592.
//
// RFC 7591: OAuth 2.0 Dynamic Client Registration Protocol
// RFC 7592: OAuth 2.0 Dynamic Client Registration Management Protocol
type ClientRegistrationStorage interface {
	// CreateClient registers a new client dynamically.
	// The clientID and clientSecret (if any) are generated by the OP.
	// The registrationAccessToken is a bearer token that the client must use
	// to manage its registration (RFC 7592).
	// The registrationURI is the unique client configuration endpoint for this client.
	CreateClient(ctx context.Context, client *RegistrationRequest, clientID, clientSecret, registrationAccessToken, registrationURI string) (*ClientRegistration, error)

	// GetClientRegistration retrieves a client registration by client_id.
	GetClientRegistration(ctx context.Context, clientID string) (*ClientRegistration, error)

	// GetClientRegistrationByToken retrieves a client registration by registration access token.
	// This is used to authenticate the client for management operations (RFC 7592).
	GetClientRegistrationByToken(ctx context.Context, registrationAccessToken string) (*ClientRegistration, error)

	// UpdateClientRegistration updates an existing client registration.
	// Only the fields provided in the update request should be updated.
	UpdateClientRegistration(ctx context.Context, clientID string, update *RegistrationUpdateRequest) (*ClientRegistration, error)

	// DeleteClientRegistration deletes a client registration.
	// This also removes the client from the OP's client store.
	DeleteClientRegistration(ctx context.Context, clientID string) error

	// ValidateInitialAccessToken validates the initial access token used for
	// the client registration endpoint. If the OP does not require an initial
	// access token, this method should return nil for the error.
	// Per RFC 7591 Section 3.1, the registration endpoint MUST be protected.
	// This implementation requires authentication (not open/public registration).
	ValidateInitialAccessToken(ctx context.Context, initialAccessToken string) error
}

// RegistrationRequest represents the client metadata sent to the registration endpoint.
// See RFC 7591 Section 2 for the full list of client metadata fields.
type RegistrationRequest struct {
	// Standard OAuth 2.0 client metadata
	RedirectURIs            []string `json:"redirect_uris,omitempty"`
	TokenEndpointAuthMethod string   `json:"token_endpoint_auth_method,omitempty"`
	GrantTypes              []string `json:"grant_types,omitempty"`
	ResponseTypes           []string `json:"response_types,omitempty"`
	ClientName              string   `json:"client_name,omitempty"`
	ClientURI               string   `json:"client_uri,omitempty"`
	LogoURI                 string   `json:"logo_uri,omitempty"`
	Scope                   string   `json:"scope,omitempty"`
	Contacts                []string `json:"contacts,omitempty"`
	TosURI                  string   `json:"tos_uri,omitempty"`
	PolicyURI               string   `json:"policy_uri,omitempty"`
	JwksURI                 string   `json:"jwks_uri,omitempty"`
	Jwks                    *JWKS    `json:"jwks,omitempty"`
	SoftwareID              string   `json:"software_id,omitempty"`
	SoftwareVersion         string   `json:"software_version,omitempty"`

	// Additional fields from RFC 7591
	SubjectType                  string   `json:"subject_type,omitempty"`
	IDTokenSignedResponseAlg     string   `json:"id_token_signed_response_alg,omitempty"`
	IDTokenEncryptedResponseAlg  string   `json:"id_token_encrypted_response_alg,omitempty"`
	IDTokenEncryptedResponseEnc  string   `json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg    string   `json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg string   `json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc string   `json:"userinfo_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg      string   `json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg   string   `json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc   string   `json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthSigningAlg  string   `json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                *int     `json:"default_max_age,omitempty"`
	RequireAuthTime              bool     `json:"require_auth_time,omitempty"`
	DefaultACRs                  []string `json:"default_acr_values,omitempty"`
	InitiateLoginURI             string   `json:"initiate_login_uri,omitempty"`
	PostLogoutRedirectURIs       []string `json:"post_logout_redirect_uris,omitempty"`
	BackChannelLogoutURI         string   `json:"backchannel_logout_uri,omitempty"`

	// Software statement (RFC 7591 Section 3.1.1)
	SoftwareStatement string `json:"software_statement,omitempty"`
}

// RegistrationUpdateRequest represents the fields that can be updated
// in a client registration (RFC 7592 Section 3.2).
// Per RFC 7592 Section 2.2, the update request MUST include all client metadata fields.
// Omitted fields MUST be treated as null or empty values (i.e., deleted).
// The request MUST NOT include "registration_access_token", "registration_client_uri",
// "client_secret_expires_at", or "client_id_issued_at".
type RegistrationUpdateRequest struct {
	// ClientID MUST be included and match the current client identifier (RFC 7592 Section 2.2)
	ClientID string `json:"client_id"`

	RedirectURIs                []string `json:"redirect_uris,omitempty"`
	TokenEndpointAuthMethod     string   `json:"token_endpoint_auth_method,omitempty"`
	GrantTypes                  []string `json:"grant_types,omitempty"`
	ResponseTypes               []string `json:"response_types,omitempty"`
	ClientName                  string   `json:"client_name,omitempty"`
	ClientURI                   string   `json:"client_uri,omitempty"`
	LogoURI                     string   `json:"logo_uri,omitempty"`
	Scope                       string   `json:"scope,omitempty"`
	Contacts                    []string `json:"contacts,omitempty"`
	TosURI                      string   `json:"tos_uri,omitempty"`
	PolicyURI                   string   `json:"policy_uri,omitempty"`
	JwksURI                     string   `json:"jwks_uri,omitempty"`
	Jwks                        *JWKS    `json:"jwks,omitempty"`
	SubjectType                 string   `json:"subject_type,omitempty"`
	IDTokenSignedResponseAlg    string   `json:"id_token_signed_response_alg,omitempty"`
	IDTokenEncryptedResponseAlg string   `json:"id_token_encrypted_response_alg,omitempty"`
	IDTokenEncryptedResponseEnc string   `json:"id_token_encrypted_response_enc,omitempty"`
	PostLogoutRedirectURIs      []string `json:"post_logout_redirect_uris,omitempty"`
	BackChannelLogoutURI        string   `json:"backchannel_logout_uri,omitempty"`
}

// ClientRegistration represents a registered client with all metadata
// and OP-generated fields.
type ClientRegistration struct {
	// Client ID (OP-generated)
	ClientID string `json:"client_id"`

	// Client Secret (OP-generated, if applicable)
	ClientSecret string `json:"client_secret,omitempty"`

	// Client ID Issued At (time the client ID was issued)
	ClientIDIssuedAt time.Time `json:"client_id_issued_at,omitempty"`

	// Client Secret Expires At (optional).
	// Per RFC 7591 Section 3.2.1, this is a JSON number representing
	// seconds since 1970-01-01T00:00:00Z (UTC).
	// A value of 0 indicates the secret does not expire.
	ClientSecretExpiresAt int64 `json:"client_secret_expires_at,omitempty"`

	// Registration Access Token (for RFC 7592 management)
	RegistrationAccessToken string `json:"registration_access_token,omitempty"`

	// Registration URI (for RFC 7592 management)
	RegistrationURI string `json:"registration_uri,omitempty"`

	// Client metadata (from the registration request)
	*RegistrationRequest

	// Token endpoint authentication method (resolved)
	TokenEndpointAuthMethod string `json:"token_endpoint_auth_method"`

	// Grant types (resolved)
	GrantTypes []string `json:"grant_types"`

	// Response types (resolved)
	ResponseTypes []string `json:"response_types"`
}

// JWKS is a minimal representation of a JSON Web Key Set for client registration.
type JWKS struct {
	Keys []map[string]interface{} `json:"keys"`
}

// Default values for client registration
const (
	DefaultTokenEndpointAuthMethod = "client_secret_basic"
	DefaultGrantType               = "authorization_code"
	DefaultResponseType            = "code"
	DefaultClientIDLength          = 32
	DefaultSecretLength            = 32
	DefaultRegistrationTokenLength = 32
)

// IsConfidential returns true if the client uses an authentication method
// that qualifies as "confidential" per OAuth 2.0.
func (c *ClientRegistration) IsConfidential() bool {
	return c.TokenEndpointAuthMethod != "none" &&
		c.TokenEndpointAuthMethod != ""
}
