//go:build ignore

// gen.go generates a TLS certificate for the storm-server HTTPS endpoint,
// signed by the CA certificate in ../ca.crt.
//
// Usage:
//
//	cd cert/web && go run gen.go
//
// Produces: server.crt, server.key
// Requires: ../ca.crt, ../ca.key (generated by ../gen.go)
package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

func main() {
	// 1. 加载CA证书和私钥
	caCertPEM, err := os.ReadFile(filepath.Join("..", "ca.crt"))
	fatal(err)
	caKeyPEM, err := os.ReadFile(filepath.Join("..", "ca.key"))
	fatal(err)

	caCertBlock, _ := pem.Decode(caCertPEM)
	caCert, err := x509.ParseCertificate(caCertBlock.Bytes)
	fatal(err)

	caKeyBlock, _ := pem.Decode(caKeyPEM)
	caKey, err := x509.ParsePKCS8PrivateKey(caKeyBlock.Bytes)
	fatal(err)

	// 2. 生成服务器密钥对
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	fatal(err)

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	fatal(err)

	// 3. 创建服务器证书模板
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   "KexCore OIDC Server",
			Organization: []string{"RoidMC Studios"},
		},
		NotBefore: time.Now(),
		NotAfter:  time.Now().Add(10 * 365 * 24 * time.Hour), // 10 years
		KeyUsage:  x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage: []x509.ExtKeyUsage{
			x509.ExtKeyUsageServerAuth,
		},
		BasicConstraintsValid: true,
		IPAddresses: []net.IP{
			net.ParseIP("127.0.0.1"),
			net.ParseIP("::1"),
			net.ParseIP("192.168.2.133"),
		},
		DNSNames: []string{
			"localhost",
			// Add your public domain here if using a real domain:
			// "kexoidc-test.example.com",
		},
	}

	// 4. 用CA签发服务器证书
	certDER, err := x509.CreateCertificate(rand.Reader, tmpl, caCert, &key.PublicKey, caKey)
	fatal(err)

	// 5. 保存服务器证书
	cf, err := os.Create("server.crt")
	fatal(err)
	pem.Encode(cf, &pem.Block{Type: "CERTIFICATE", Bytes: certDER})
	cf.Close()

	// 6. 保存服务器私钥
	kf, err := os.Create("server.key")
	fatal(err)
	kb, err := x509.MarshalECPrivateKey(key)
	fatal(err)
	pem.Encode(kf, &pem.Block{Type: "EC PRIVATE KEY", Bytes: kb})
	kf.Close()

	println("Done: server.crt, server.key")
	println("Signed by: KexCore FAPI Test CA")
	println("Valid for: localhost, 127.0.0.1, ::1, 192.168.2.133")
	println("Expires: 10 years")
}

func fatal(err error) {
	if err != nil {
		panic(err)
	}
}
